apiVersion: v1
kind: Service
metadata:
  name: github-webhook-eventsource
  namespace: argo-events
spec:
  type: NodePort
  ports:
  - port: 12000
    targetPort: 12000
  selector:
    app: github-webhook-eventsource

