apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: github-dep
      eventSourceName: github-webhook
      eventName: example
  triggers:
    - template:
        name: trigger-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-triggered-workflow-
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: busybox
                      command: [sh, -c]
                      args: ["echo 'GitHub webhook received and!'"]

